DROP DATABASE IF EXISTS anime_olap;
CREATE DATABASE anime_olap;

USE anime_olap;

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE (
  ID_GENRE INT NOT NULL,
  GENRE VARCHAR(30)
);

DROP TABLE IF EXISTS ANIME;
CREATE TABLE ANIME (
  ID_ANIME INT NOT NULL,
  ANIME_NAME VARCHAR(255),
  FAVORITES FLOAT,
  START_DATE DATE,
  FINISH_DATE DATE
);

DROP TABLE IF EXISTS CLASSIFICATION;
CREATE TABLE CLASSIFICATION (
  ID_CLASSIFICATION INT NOT NULL,
  CLASSIFICATION VARCHAR(30)
);

DROP TABLE IF EXISTS SOURCES;
CREATE TABLE SOURCES (
  ID_SOURCES INT NOT NULL,
  SOURCES VARCHAR(30)
);

DROP TABLE IF EXISTS TYPES;
CREATE TABLE TYPES (
  ID_TYPES INT NOT NULL,
  TYPES VARCHAR(50)
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  ID_USER INT NOT NULL,
  USERNAME VARCHAR(50),
  LOCATION VARCHAR(255),
  COMPLETED FLOAT,
  DROPPED FLOAT,
  PLAN_TO_WATCH FLOAT,
  WATCHING FLOAT
);

DROP TABLE IF EXISTS GENRE_ANIME;
CREATE TABLE GENRE_ANIME(
	ID_ANIME INT NOT NULL,
	ID_GENRE INT NOT NULL
);

DROP TABLE IF EXISTS ANIME_HECHOS;
CREATE TABLE ANIME_HECHOS(
	ID_ANIME INT NOT NULL,
	ID_CLASSIFICATION INT NOT NULL,
	ID_SOURCES INT NOT NULL,
	ID_USER INT NOT NULL,
	ID_TYPES INT NOT NULL,
	RATING INT
);


ALTER TABLE GENRE
ADD PRIMARY KEY (ID_GENRE);

ALTER TABLE ANIME
ADD PRIMARY KEY (ID_ANIME);

ALTER TABLE CLASSIFICATION
ADD PRIMARY KEY (ID_CLASSIFICATION);

ALTER TABLE SOURCES
ADD PRIMARY KEY (ID_SOURCES);

ALTER TABLE TYPES
ADD PRIMARY KEY (ID_TYPES);

ALTER TABLE USERS
ADD PRIMARY KEY (ID_USER);

ALTER TABLE GENRE_ANIME
ADD PRIMARY KEY (ID_ANIME, ID_GENRE);

ALTER TABLE ANIME_HECHOS
ADD PRIMARY KEY (ID_ANIME, ID_CLASSIFICATION, ID_SOURCES, ID_USER, ID_TYPES);


ALTER TABLE GENRE_ANIME
ADD FOREIGN KEY (ID_ANIME) REFERENCES ANIME(ID_ANIME),
ADD FOREIGN KEY (ID_GENRE) REFERENCES GENRE(ID_GENRE);


ALTER TABLE ANIME_HECHOS
ADD FOREIGN KEY (ID_ANIME) REFERENCES ANIME(ID_ANIME),
ADD FOREIGN KEY (ID_CLASSIFICATION) REFERENCES CLASSIFICATION(ID_CLASSIFICATION),
ADD FOREIGN KEY (ID_SOURCES) REFERENCES SOURCES(ID_SOURCES),
ADD FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER),
ADD FOREIGN KEY (ID_TYPES) REFERENCES TYPES(ID_TYPES);
